Repository wecode-bootcamp-korea/41-backend-westagram-2, pull requests merged in 2022-12, with the labels that each got.

#2 [김용신] Assignment 1 | Westagram Backend Project - Express 초기 환경세팅
  yongshin/.env.sample
  yongshin/.gitignore
  yongshin/app.js
  yongshin/package-lock.json
  yongshin/package.json
Labels: 멘토 리뷰 요청

#1 [41기 김광휘] Assignment 1 | Westagram Backend Project - Express 초기 환경세팅
  kwanghwi/myapp/.env sample
  kwanghwi/myapp/.gitignore
  kwanghwi/myapp/app.js
  kwanghwi/myapp/package-lock.json
  kwanghwi/myapp/package.json
Labels: 완료

#3 [김동규] Assignment 1: Express API - 초기 환경 세팅
  dongkyu/initial-settings-express/myapp/.env.sample
  dongkyu/initial-settings-express/myapp/.gitignore
  dongkyu/initial-settings-express/myapp/app.js
  dongkyu/initial-settings-express/myapp/package-lock.json
  dongkyu/initial-settings-express/myapp/package.json
Labels: 멘토 리뷰 요청

#8 [41기 이민규] Assignment 1: Express API - 초기 환경 세팅
  minkyu/.env.sample
  minkyu/.gitignore
  minkyu/app.js
  minkyu/package-lock.json
  minkyu/package.json
Labels: 멘토 리뷰 요청, 수정 요청

#4 [41기 김광휘] Assignment 2 | Westagram Backend Project - 유저 회원가입 하기
  kwanghwi/myapp/.gitignore
  kwanghwi/myapp/app.js
  kwanghwi/myapp/db/migrations/20221220062637_create_users_table.sql
  kwanghwi/myapp/db/migrations/20221220062647_create_posts_table.sql
  kwanghwi/myapp/db/migrations/20221220062656_create_likes_table.sql
  kwanghwi/myapp/package-lock.json
  kwanghwi/myapp/package.json
Labels: 멘토 리뷰 요청

#9 [김동규] Assignment 2 | Westagram Backend Project - 유저 회원가입 하기
  dongkyu/initial-settings-express/myapp/app.js
  dongkyu/initial-settings-express/myapp/db/migrations/20221221124709_create_users_table.sql
Labels: 멘토 리뷰 요청

#12 [김동규] Assignment 3, 4, 5 | Westagram Backend Project - CRUD
  dongkyu/initial-settings-express/myapp/app.js
  dongkyu/initial-settings-express/myapp/db/migrations/20221222040455_create_posts_table.sql
Labels: 멘토 리뷰 요청

#10 [41기 김광휘] Assignment (3, 4, 5, 6, 7, 8) - CRUD PR
  kwanghwi/myapp/app.js
  kwanghwi/myapp/db/migrations/20221220062637_create_users_table.sql
  kwanghwi/myapp/db/migrations/20221220062647_create_posts_table.sql
Labels: 멘토 리뷰 요청

#13 41기 이민규] Assignment 2 | Westagram Backend Project - 유저 회원가입 하기
  minkyu/.env.sample
  minkyu/.gitignore
  minkyu/app.js
  minkyu/db/migrations/20221222105635_users.sql
  minkyu/db/migrations/20221226020119_posts.sql
  minkyu/db/schema.sql
  minkyu/package-lock.json
  minkyu/package.json
Labels: 멘토 리뷰 요청

#15 [41기 김광휘] Assignment 1 | Westagram Backend Project - Bcrypt를 이용하여 비밀번호 암호화하기
  kwanghwi/myapp/app.js
Labels: 멘토 리뷰 요청

#16 [41기 김광휘] Assignment 2 | Westagram Backend Project - Bcrypt Verification 및 JWT 발급하기
  kwanghwi/myapp/app.js
  kwanghwi/myapp/package-lock.json
  kwanghwi/myapp/package.json
Labels: 멘토 리뷰 요청

#14 [김동규] Assignment 6, 7, 8 | Westagram Backend Project - CRUD
  dongkyu/initial-settings-express/myapp/.gitignore
  dongkyu/initial-settings-express/myapp/app.js
  dongkyu/initial-settings-express/myapp/db/migrations/20221225093135_create_likes_table.sql
  dongkyu/initial-settings-express/myapp/package-lock.json
  dongkyu/initial-settings-express/myapp/package.json
Labels: 멘토 리뷰 요청

#20 [김동규] Assignment 1 | Westagram Backend Project - Bcrypt를 이용하여 비밀번호 암호화하기
  dongkyu/initial-settings-express/myapp/app.js
Labels: 멘토 리뷰 요청
